name: dde_env
channels:
  - defaults
dependencies:
  - arrow-cpp=19.0.0=h800e9c8_5
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313h2cb717b_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.9.9=haa95532_0
  - cramjam=2.9.1=py313hbdb9fe4_0
  - expat=2.7.1=h8ddb27b_0
  - fastparquet=2024.11.0=py313h2cb717b_1
  - freetype=2.13.3=h0620614_0
  - fsspec=2025.7.0=py313h4442805_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9f=ha349fce_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libmpdec=4.0.0=h827c3e9_0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-base=3.10.6=py313h26e45b9_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=1.3.11=py313h5810407_1
  - mkl_random=1.2.8=py313hedd7022_1
  - numexpr=2.11.0=py313h7660c64_1
  - numpy=2.3.3=py313h050da96_0
  - numpy-base=2.3.3=py313h1e017a8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - orc=2.1.1=hd1c1d5c_0
  - packaging=25.0=py313haa95532_0
  - pandas=2.3.2=py313h42c1672_0
  - pip=25.2=pyhc872135_0
  - pyarrow=19.0.0=py313h885b0b7_2
  - python=3.13.7=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313haa95532_0
  - re2=2024.07.02=h214f63a_0
  - seaborn=0.13.2=py313haa95532_3
  - six=1.17.0=py313haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - build==1.3.0
      - cachecontrol==0.14.3
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - cleo==2.1.0
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.3
      - crashtest==0.4.1
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distlib==0.4.0
      - dulwich==0.24.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - findpython==0.7.0
      - fonttools==4.60.0
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - installer==0.7.0
      - ipykernel==6.30.1
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - keyring==25.6.0
      - kiwisolver==1.4.9
      - lark==1.3.0
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - more-itertools==10.8.0
      - msgpack==1.1.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pbs-installer==2025.9.18
      - pillow==11.3.0
      - pkginfo==1.12.1.2
      - platformdirs==4.4.0
      - poetry==2.2.0
      - poetry-core==2.2.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - python-json-logger==3.3.0
      - pywin32==311
      - pywin32-ctypes==0.2.3
      - pywinpty==3.0.0
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - rapidfuzz==3.14.1
      - referencing==0.36.2
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - send2trash==1.8.3
      - setuptools==80.9.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomlkit==0.13.3
      - tornado==6.5.2
      - traitlets==5.14.3
      - trove-classifiers==2025.9.11.17
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.15.0
      - uri-template==1.3.0
      - urllib3==2.5.0
      - virtualenv==20.34.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wget==3.2
      - zstandard==0.25.0
prefix: C:\Users\rishr\miniconda3\envs\dde_env
